name: Build
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release Tag'
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
      - name: Download JI jar
        run: |
          mkdir -p ../Fiji.app/jars
          wget -O ../Fiji.app/jars/ij-1.53t.jar https://repo1.maven.org/maven2/net/imagej/ij/1.53t/ij-1.53t.jar
      - name: Build the plugin
        run: |
          ant -Dplatforms.JDK_1.8.home=$JAVA_HOME -noinput -buildfile build.xml
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: IJ Plugin
          path: ./dist/*.jar
          retention-days: 32
      - name: Checkout dev-binaries
        uses: actions/checkout@v3
        with:
          ref: dev-binaries
          fetch-depth: 0
          path: _git_tmp
      - name: Upload dev-binaries
        run: |
          cp dist/*.jar _git_tmp/
          cd _git_tmp
          git config --global credential.helper ""
          git config --global --add credential.helper store
          echo "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com" >> ~/.git-credentials
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git add -A
          git commit --amend -m "Latest development binaries"
          git push --force
      - name: Release
        uses: softprops/action-gh-release@v1
        if: "${{ github.event.inputs.tag_name != '' }}"
        with:
          files: dist/*.jar
          draft: false
          tag_name: ${{ github.event.inputs.tag_name }}
          fail_on_unmatched_files: true
          target_commitish: ${{ env.commit_hash }}
          generate_release_notes: true
  
